### ISSUE TITLE
Set default values for the distractors in Distraction Task

### ISSUE THREAD

**Issue by breznak** [breznak/openDS#36]
These should be "optimal" values that will be used in reproducible experiments. 
- [x] "Default" button
- [ ] apply the defaults on our experiment by default
- [ ] optimize the default parameters

**Comment by JohnnyMarek** [comment]
This is already implemented as follows: Default button is in the options menu. After clicking it resets the options to 0s and applies some default values from the code (will change it to txt). The settings are: rain intensity 20, collect prob. 30 and box prob 30.

**Comment by breznak** [comment]
> applies some default values from the code (will change it to txt)

This will be great! 

> After clicking it resets the options to 0s and applies some default values

this was my comment in the PR: (if the reset() method is implemented by us, not upstream?) why not do it like 

```
void reset() {
 // set to 0s
 try {
  loadDefaults(some/config.txt);
 }
}
```

>  Default button is in the options menu. After clicking it

This was my last "problem": apply the defaults by default (=when the window opens), not only after clicking it.

**Comment by JohnnyMarek** [comment]
The void reset() works only to put 0s everywhere. The function which loads the data is clickInstButton(). It works like this:

clickInstButton() {
  if  (!clicked) {
    // set to 0s, load defaults
    reset();
    setDefaults(); // this will work from txt later
    clicked = !clicked;
  } else {
     /*this will only reset to 0s after it is clicked second time (to automatically delete default options 
     if the user changes his mind and doesn't want to drag all sliders to 0s. */
   reset();
   clicked = !clicked;
}

I can make that the load from txt will work at the start of the program and switch the "clicked" to true for the beginning.

**Comment by breznak** [comment]
Ah, I see. Just i minor improvement, if possible: do you have to keep 2 variables for one option? (checkbox 'clicked' and the actual slide bar)

Can we do sth like:

```
SlideBar rainIntensity = new SlideBar(...);
CheckBox rainToggle = new CheckBox() { actionListener{...}}; //on action: if(rainIntensity.enabled()) { rainIntensity.disable()} else {/*otherwise*/};
```

Or let's just completely drop the checkbox and use only the slideBar (0 means disabled) 
That sounds like the cleanest option to me, what do you think?

**Comment by JohnnyMarek** [comment]
Maybe i will delete the checkboxes, it really sounds redundant to keep them since you still have to set some probability value anyway. I will look at it after i solve urgent tasks.
