### ISSUE TITLE
Design and implement cognitive distractors

### ISSUE THREAD

**Issue by breznak** [breznak/openDS#4]
The distractors are (random) disruptive elements or tasks, that the human driver must handle during his main task (driving). 

List: 
- [ ] suicidal pedestrian 
  - [ ] look like a "human"
- [x] random obstacle (box) on the road
  - [ ] Red/Green
- [ ] image skin box (for photos of faces)
- [ ] darkening of the screen (fog, snow,..)
  - FIX
- [x] audio input requiring memorization and later input
  - [x] play sound
  - [ ] "conversation" (remember some info) (how? text2speech?, recorded)
- [x] signs (that one must remember, ignore, etc: eg: 2x2=?, What is the capital of Czech rep.?, 
  Remember: "Cucumbers",...)
  - [ ] sign along the road (with text) - can we use text as texture?? - road detection
  - [x] popup screen with text (+input) (eg. math equations, ...)
  - [ ] questions/answers input as CSV ("How are you?", "good", "[good]", 1/0)
  - [ ] Enter = confirm
  - [ ] correct? (lowercase,...)

The `distractors` appear either randomly (#3) or as designed (#2) 

They could have these properties: 
- significance (hit a person=-100, hit a box=-10, miss a sign=-2,...)
- ~~visibility range~~
- "correctly answered?" (person not hit, sign remembered and evaluated correctly, ...) 
- logged 

Implemented in #15

**Comment by JohnnyMarek** [comment]
Starting work on this issue in friday 11.3. will update soon
