### ISSUE TITLE
Design a cognitive complexity score

### ISSUE THREAD

**Issue by breznak** [breznak/openDS#7]
A function of time that outputs a score 0.0..1.0 of cognitive complexity of a given situation. 

Example attributes that account for the score: 
- car speed
- number of cars on the scene
- road difficulty (highway / city road / cross road, ..)
- number of distractors currently active (#4)
- weather conditions (fog, ...)
- simulation sensitivity (eg. wheel's sensitivity) 

The values are logged to the session's run audit.

TODO: 
- [ ] a function can list all objects in given radius from the car (current distractors)
- [ ] weighted sum of distractors (correctly answered, hit/missed, ...)
- [ ] audit/log

**Comment by JohnnyMarek** [comment]
Work on this issue starts also Friday, 11.3.16. With developing cognitive distractors i will create scoring function based on difficulty of situation.
