### ISSUE TITLE
Application is stuck on the "Loading" screen

### ISSUE THREAD

**Issue by zephirefaith** [breznak/openDS#71]
I am trying to run the open source version of OpenDS on an Ubuntu 14.04 machine with Nvidia GeForce GTX 980. I have installed Netbeans 8.2 via the co-bundle installer with JDK 8. I do not get any build errors but the OpenDS window is stuck on the "Loading" screen after starting a task. Also my mouse is taken over by OpenDS when it starts up and exiting via Esc key does not work, I have been exiting out of the window by killing it using its PID. Not sure if this is the expected behavior but just jotting it down in case this helps.

Following is my run dump from Netbeans output window -- 

```
ant -f /home/pparashar/git/openDS-oss/IDEs/netbeans -Dnb.internal.action.name=run run
init:
Deleting: /home/pparashar/git/openDS-oss/IDEs/netbeans/build/built-jar.properties
deps-jar:
Updating property file: /home/pparashar/git/openDS-oss/IDEs/netbeans/build/built-jar.properties
compile:
run:
Executing Startup Properties
Loading: net.java.games.input.LinuxEnvironmentPlugin
Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)

Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)

Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)

Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)

Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)

Failed to open device (/dev/input/event9): Failed to open device /dev/input/event9 (13)

Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)

Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)

Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)

Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)

Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)

Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)

Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)

Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)

Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)

Linux plugin claims to have found 0 controllers
/home/pparashar/git/openDS-oss/IDEs/netbeans/nbproject/build-impl.xml:1052: The following error occurred while executing this line:
/home/pparashar/git/openDS-oss/IDEs/netbeans/nbproject/build-impl.xml:817: Java returned: 137
BUILD FAILED (total time: 1 minute 0 seconds)

```

Edit: After running the jar file from the command line I get repetitive errors for all the driving tasks of the form:
``` bash
File '/path/to/openDS-oss/assets/DrivingTasks/Projects/<insert driving task>/<driving_task>.xml'
points to an invalid scene file: /path/to/openDS-oss/assets/DrivingTasks/Projects/<driving_task>/scene.xml
```

**Comment by breznak** [comment]
Thanks for reporting! I'll test it. But I'm on a holiday for 3weeks, if you don't resolve it by then please ping me after that time.

**Comment by zephirefaith** [comment]
I don't think I am going to continue with the open source version of OpenDS until then but after going down this rabbit-hole, I realized the problem lies with the validation of a driving task's scene.xml against the built-in scene schema. Specifically, this function seems to be hanging the system up:
https://github.com/breznak/openDS-oss/blob/master/src/eu/opends/drivingTask/DrivingTaskDataQuery.java#L529-L551

Hope this helps. Have fun on your vacation :)!

**Comment by breznak** [comment]
Thanks for the detailed analysis of the problem! That will be useful. 
Does it mean the err you are getting only happens on scenes that are "completely different" and not only slightly-modified from the orig.? 

Also, does it happen on the latest upstream version? We are falling one release behind. 

Thanks! :tada:

**Comment by zephirefaith** [comment]
Actually I am seeing this error while trying to run the built-in scenes. The code seems to be invalidating the stored scenes against your XML schema.

I do not know about your second question though, I was not aware there is another open source version?
